import BlogsContainer from "@/components/BlogsContainer";
import Head from "next/head";

// export const metadata: Metadata = {
//   title: 'Blog',
//   description: 'Generated by create next app',
// }
function page() {
  return (
    <div>
      <Head>
        <title>My page title</title>
        <meta property="og:title" content="My page title" key="title" />
      </Head>
      <div className="mt-24">
        <h1 className="font-bold text-3xl  -tracking-tight mb-6">
        Latest Writing
        </h1>
        <BlogsContainer />
      </div>
    </div>
  );
}

export default page;
